language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
after_success:
  - julia -e 'cd(Pkg.dir("Gettext")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
