name = "Gettext"
uuid = "a6aca261-61b0-5b33-a99a-e9c977ffa089"
version = "0.1.0"

[deps]
GettextRuntime_jll = "b0724c58-0f36-5564-988d-3bb0596ebc4a"

[compat]
GettextRuntime_jll = "0.22.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
